<!doctype html>  
<head>
    <base href="<?PHP echo $this->base; ?>" /> 

    <meta charset="utf-8">

    <title><?PHP echo trim(\F3::get('html_title')); ?></title>
    
    <meta name="description" content="selfoss" />
    <meta name="author" content="Tobias Zeising" />

    <!--  Mobile viewport optimized: j.mp/bplateviewport -->
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1" />
    
    <!--  Add support for fullscreen Webapp on iPhone 5 -->
    <meta name="viewport" content="initial-scale=1, user-scalable=no, maximum-scale=1" media="(device-height: 568px)" />
    
    <!-- app 'behaviour' when adding link to iDevice springboard -->
    <meta name="apple-mobile-web-app-capable" content="yes" />

    <!-- icons -->
    <link rel="apple-touch-icon-precomposed" href="icon-128x128.png" />
    <link rel="icon" type="image/png" href="icon-32x32.png" />
    <link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />

    <!-- Toolbar color from Chrome for Android -->
    <meta name="theme-color" content="#191718" />

    <!-- all css definitions -->
    <?PHP if(\F3::get('use_system_font')!=true) : ?>
        <link rel="stylesheet" href="css/fonts.css" />
    <?PHP endif; ?>
    <link rel="stylesheet" href="<?PHP echo \helpers\View::getGlobalCssFileName(); ?>" />
    <link href="/bs/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container-fluid">
        <div style="margin-top:50%;">
            <form action="/guid" method="post">
                <div class="form-group">
                    <?php if (!empty($_SESSION['nickname'])) { ?>
                        <div class="alert alert-info">
                            <div class="row">
                                <div class="col-xs-2"></div>
                                <div class="col-xs-8">
                                    <p>Guid：<?php echo $_SESSION['guid']; ?></p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-2"></div>
                                <div class="col-xs-8">
                                    <p>公司缩写：<?php echo $_SESSION['nickname']; ?></p>
                                </div>
                            </div>
                        </div>
                    <?php } else { ?>
                        <label style="width:100%" for="guid">请输入企业号</label>
                        <input id="guid" name="guid" class="form-control" placeholder="请输入企业号">
                    <?php } ?>
                </div>
                <div class="text-center">
                    <?php if (!empty($_SESSION['nickname'])) { ?>
                        <button class="btn btn-danger" onclick="javascript:window.parent.location.href='/guid/logout'">退出</button>
                        <button class="btn btn-info" onclick="javascript:window.parent.location.href='/'">关闭窗口</button>
                    <?php } else { ?>
                        <button type="submit" class="btn btn-info">登陆</button>
                        <span class="btn btn-info" onclick="javascript:window.parent.location.href='/'">关闭窗口</span>
                    <?php } ?>
                </div>
            </form>
        </div>
    </div>
</body>
</html>
