<!doctype html>
<html lang="<?PHP echo \F3::get('language'); ?>">
<head>
    <base href="<?PHP echo $this->base; ?>" /> 

    <meta charset="utf-8">

    <title><?PHP echo trim(\F3::get('html_title')); echo $this->statsUnread>0 ? ' ('.$this->statsUnread.')' : ''; ?></title>
    
    <meta name="description" content="selfoss" />
    <meta name="author" content="Tobias Zeising" />
    <meta name="version" content="<?PHP echo \F3::get('version'); ?>" />
    <meta name="referrer" content="no-referrer" />

    <!--  Mobile viewport optimized: j.mp/bplateviewport -->
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1" />
    
    <!--  Add support for fullscreen Webapp on iPhone 5 -->
    <meta name="viewport" content="initial-scale=1, user-scalable=no, maximum-scale=1" media="(device-height: 568px)" />
    
    <!-- app 'behaviour' when adding link to iDevice springboard -->
    <meta name="apple-mobile-web-app-capable" content="yes" />
    
    <!-- app 'behaviour' when adding link to Android Home  -->
    <meta name="mobile-web-app-capable" content="yes" />

    <!-- app tile and notification when adding link to Windows 8 start screen -->
    <meta name="application-name" content="Selfoss" />
    <meta name="msapplication-TileColor" content="#3d6d69" />
    <meta name="msapplication-square70x70logo" content="<?php echo $this->base; ?>win8-70-icon.png" />
    <meta name="msapplication-square150x150logo" content="<?php echo $this->base; ?>win8-150-icon.png" />
    <meta name="msapplication-wide310x150logo" content="<?php echo $this->base; ?>win8-150-icon.png" />
    <meta name="msapplication-square310x310logo" content="<?php echo $this->base; ?>win8-310-icon.png" />
    <meta name="msapplication-notification" content="cycle=1; frequency=30; polling-uri=<?php echo $this->base; ?>win8notifs" />
    <meta name="msapplication-badge" content="frequency=30; polling-uri=<?php echo $this->base; ?>badge" />

    <!--  RSS Feed -->
    <link rel="alternate" type="application/rss+xml" title="RSS Feed" href="feed" />
    <!-- <link href="/bs/css/bootstrap.min.css" rel="stylesheet"> -->
    <!-- icons -->
    <link rel="apple-touch-icon-precomposed" href="icon-128x128.png" />
    <link rel="icon" type="image/png" href="icon-32x32.png" />
    <link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />

    <!-- Toolbar color from Chrome for Android -->
    <meta name="theme-color" content="#191718" />

    <!-- all css definitions -->
    <?PHP if(\F3::get('use_system_font')!=true) : ?>
        <link rel="stylesheet" href="css/fonts.css" />
    <?PHP endif; ?>
    <link rel="stylesheet" href="<?PHP echo \helpers\View::getGlobalCssFileName(); ?>" />

</head>
<body class="
    <?PHP echo $this->publicMode===true ? "publicmode" : ""; ?>
    <?PHP echo $this->loggedin===true ? "loggedin" : "notloggedin"; ?> 
    <?PHP echo \F3::get('auto_mark_as_read')==1 ? "auto_mark_as_read" : ""; ?>
">
    
    <div id="error"></div>
    
    <!-- language settings for jQuery -->
    <span id="lang"
        data-mark="<?PHP echo \F3::get('lang_mark'); ?>"
        data-unmark="<?PHP echo \F3::get('lang_unmark'); ?>"
        data-star="<?PHP echo \F3::get('lang_star'); ?>"
        data-unstar="<?PHP echo \F3::get('lang_unstar'); ?>"
        data-source_warn="<?PHP echo \F3::get('lang_source_warn'); ?>"
        data-source_saved="<?PHP echo \F3::get('lang_source_saved'); ?>"
        data-source_edit="<?PHP echo \F3::get('lang_source_edit'); ?>"></span>

    <!-- other settings -->
    <span id="config"
        data-anonymizer="<?PHP echo \helpers\Anonymizer::getAnonymizer(); ?>"
        data-share="<?PHP echo \F3::get('share'); ?>"
        data-wallabag="<?PHP echo \F3::get('wallabag'); ?>"
        data-wordpress="<?PHP echo \F3::get('wordpress'); ?>"
        data-auto_mark_as_read="<?PHP echo \F3::get('auto_mark_as_read'); ?>"
        data-auto_collapse="<?PHP echo \F3::get('auto_collapse'); ?>"
        data-auto_stream_more="<?PHP echo \F3::get('auto_stream_more'); ?>"
        data-load_images_on_mobile="<?PHP echo \F3::get('load_images_on_mobile'); ?>"
        data-items_perpage="<?PHP echo \F3::get('items_perpage'); ?>"
        data-auto_hide_read_on_mobile="<?PHP echo \F3::get('auto_hide_read_on_mobile'); ?>"
        data-html_title="<?PHP echo trim(\F3::get('html_title')); ?>"></span>

    <!-- menue open for smartphone -->
    <style type="text/css">
        #nav-mobile-login {
            position:absolute;
            width:29px;
            height:29px;
            background:url(images/nav-user.png) no-repeat center;
            background-size:29px 29px;
            padding:11px 21px 11px 15px;
        }
        #nav-mobile-logo {
            position:absolute;
            /*width:1px;*/
            height:1px;
            left:50%;
            top:5px;
            margin-left:-48px;
            background:no-repeat;
            background-size:1px 1px;
        }
        #nav-mobile-logo span {
            color: white;
            position: relative;
            left: 25px;
            top: 5px;
            display: none;
        }
        #nav-mobile {
            /*position:relative;*/
            display:block;
            background:#191718;
            border-bottom:3px solid #3d6d69;
            width:100%;
            height:50px;
            position: fixed;
            z-index: 100;
            top: 0px;
        }

        .entry-smartphone-share {
            display: none;
        }
        span.unread-count1.unread1 {
            background-color: #E74C3C;
            border-radius: 30px;
            color: white !important;
            font-size:0.6em !important;
            font-weight: normal;
            min-width: 8px;
            padding: 0 5px 0 5px;
            margin-left: 5px;
            vertical-align:baseline !important;
            display: inline !important;
            width: 20px;
        }
    </style>

    <div id="nav-mobile">
<!--        <a href="/guid">-->
<!--            <div id="nav-mobile-login"></div>-->
<!--        </a>-->
        <div id="nav-mobile-login"></div>

        <div id="nav-mobile-logo">
            <?php session_start(); if (!empty($_SESSION['nickname'])) { ?>
                <span class="unread-count1 unread1"><?PHP echo $_SESSION['nickname']; ?></span>
            <?php } else { ?>
                <span class="unread-count1 unread1">微播</span>
            <?php } ?>
        </div>
        <div id="nav-mobile-settings"></div>
    </div>
    
    <!-- navigation -->
    <div id="nav" role="navigation">
        <!-- <div id="nav-logo"></div> -->
        <button id="nav-mark"><?PHP //echo \F3::get('lang_markread')?></button>

        <?PHP $active = (\F3::get('homepage')) ? \F3::get('homepage') : 'newest' ?>
        <h2 id="nav-filter-title" style="display:none"><?PHP echo \F3::get('lang_filter') ?></h2>
        <ul id="nav-filter" style="display:none">
            <li id="nav-filter-newest" class="nav-filter-newest<?PHP if($active=='newest') : ?> active<?PHP endif; ?>" role="link" tabindex="0"><?PHP echo \F3::get('lang_newest')?> <span><?PHP echo $this->statsAll; ?></span></li>
            <li id="nav-filter-unread" class="nav-filter-unread<?PHP if($active=='unread') : ?> active<?PHP endif; ?>" role="link" tabindex="0"><?PHP echo \F3::get('lang_unread')?> <span class="unread-count<?PHP echo $this->statsUnread>0 ? ' unread' : ''; ?>">微播</span></li>
            <li id="nav-filter-starred" class="nav-filter-starred<?PHP if($active=='starred') : ?> active<?PHP endif; ?>" role="link" tabindex="0"><?PHP echo \F3::get('lang_starred') ?> <span><?PHP echo $this->statsStarred; ?></span></li>
        </ul>

        <hr>

        <div id="nav-tags-wrapper">
        <h2 id="nav-tags-title" class="nav-tags-expanded" tabindex="0" aria-haspopup="true" aria-expanded="true"><?PHP echo \F3::get('lang_tags') ?></h2>
        <ul id="nav-tags">
            <li class="active nav-tags-all" role="link" tabindex="0"><?PHP echo \F3::get('lang_alltags')?></li>
            <?PHP echo $this->tags; ?>
        </ul>
        <h2 id="nav-sources-title" class="nav-sources-collapsed" tabindex="0" aria-haspopup="true" aria-expanded="false"><?PHP //echo \F3::get('lang_sources') ?></h2>
        <ul id="nav-sources">
            <?PHP //echo $this->sources; ?>
        </ul>
        </div>
        
        <hr>
        
        <!-- navigation search input just for smartphone version -->
        <div id="nav-search" role="search">
            <input style="display:none" type="search" id="nav-search-term"> <input style="display:none" type="button" id="nav-search-button" value="<?PHP echo \F3::get('lang_searchbutton')?>">
            <hr>
        </div>
        
        <?PHP if($this->loggedin===true && \F3::get('auth')->enabled()===false) : ?>
        <button style="display:none" id="nav-refresh" title="<?PHP echo trim(\F3::get('lang_refreshbutton')); ?>" class="nologin"></button>
        <button style="display:none" id="nav-settings" title="<?PHP echo trim(\F3::get('lang_settingsbutton')); ?>" class="nologin"></button>
        <?PHP endif; ?>
        
        <?PHP if($this->loggedin===true && \F3::get('auth')->enabled()===true) : ?>
        <button id="nav-refresh" title="<?PHP echo trim(\F3::get('lang_refreshbutton')); ?>"></button>
        <button id="nav-settings" title="<?PHP echo trim(\F3::get('lang_settingsbutton')); ?>"></button>
        <button id="nav-logout" title="<?PHP echo trim(\F3::get('lang_logoutbutton')); ?>"></button>
        <?PHP endif; ?>
        
        <?PHP if($this->loggedin===false) : ?>
        <button id="nav-login" title="<?PHP echo trim(\F3::get('lang_loginbutton')); ?>"></button>
        <?PHP endif; ?>
        
        <a  style="display:none" id="nav-copyright" href="http://selfoss.aditu.de" target="_blank">selfoss <?PHP echo \F3::get('version'); ?></a>
    </div>
    
    <!-- search -->
    <div id="search" role="search">
        <input type="search" id="search-term">
        <button id="search-remove" title="<?PHP echo \F3::get('lang_searchremove')?>"><img src="public/images/remove.png" alt=""></button>
        <button id="search-button" title="<?PHP echo \F3::get('lang_searchbutton')?>"><img src="public/images/search.png" alt=""></button>
    </div>
    
    <ul id="search-list">
    </ul>
    
    <!-- unread count below the fold -->
    <div id="floating-unread" aria-hidden="true">
        <span class="floating-unread-count"></span>
        <div class="bottom-triangle"></div>
    </div>
    <br><br>
    <!-- content -->
    <div id="content" role="main">
        <?PHP echo $this->content; ?>
    </div>
    
    <div class="stream-error"><?PHP echo trim(\F3::get('lang_streamerror')); ?></div>

    <!-- fullscreen popup -->
    <div id="fullscreen-entry"></div>
    <script src="<?PHP echo \helpers\View::getGlobalJsFileName(); ?>"></script>
    <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          ...
        </div>
      </div>
    </div>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/bs/js/bootstrap.min.js"></script>
<!--    <div id="model" style="background-color: #0da3fa;display: none;position: fixed;left: 0;right: 0;margin:auto;top:150px;text-align: center" width="100px" height="100px">-->
<!--        <iframe src="/guid"></iframe>-->
<!--    </div>-->
    <iframe id="model" src="/guid" style="background-color: #0da3fa;display: none;position: fixed;left: 0;right: 0;margin:auto;top:150px;text-align: center" width="200px" height="200px">
<!--        <iframe src="/guid"></iframe>-->
    </iframe>
<script>
    $('#nav-mobile-login').click(function () {
        $('#model').css('display','block');
    })
    if(typeof(JsInterface) != "undefined"){
        guid = "<?php echo isset($_SESSION['guid']) ? $_SESSION['guid'] : 'null'; ?>";
        JsInterface.setGuid(guid);
        var test = JsInterface.getGuid();
        console.log(test);
    }
</script>
</body>
</html>
